all:
	g++ -I"/home/tom/R/x86_64-pc-linux-gnu-library/3.5/Rhdf5lib/include" hdf5_test.cpp -o hdf5_test.o
	g++ hdf5_test.o /home/tom/R/x86_64-pc-linux-gnu-library/3.5/Rhdf5lib/lib/libhdf5_cpp.a /home/tom/R/x86_64-pc-linux-gnu-library/3.5/Rhdf5lib/lib/libhdf5.a /home/tom/R/x86_64-pc-linux-gnu-library/3.5/Rhdf5lib/lib/libsz.a -lz